# Generated by Django 5.1.7 on 2025-04-05 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text="Brief summary of the ticket's purpose.", max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the issue or request.')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('CLOSED', 'Closed')], db_index=True, default='NEW', help_text='The current status of the ticket.', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, default='MEDIUM', help_text='The urgency level of the ticket.', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the ticket was created.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the ticket was last modified.')),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('assignee', models.ForeignKey(blank=True, help_text='The user currently assigned to resolve the ticket (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(help_text='The user who submitted the ticket.', on_delete=django.db.models.deletion.PROTECT, related_name='reported_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-last_updated'],
            },
        ),
    ]
