# Generated by Django 5.1.7 on 2025-04-05 11:03

import acme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment related to the ticket.', null=True, upload_to=acme.models.ticket_attachment_path),
        ),
    ]
