# Generated by Django 5.1.7 on 2025-04-05 11:50

import acme.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0002_ticket_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique name or identifier for the machine (e.g., 'CNC Mill 01', 'Assembly Line 3').", max_length=100, unique=True)),
                ('location', models.CharField(blank=True, help_text="Physical location of the machine (e.g., 'Shop Floor A', 'Building 2').", max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, help_text="Manufacturer's serial number (optional).", max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('BUG', 'Bug Report'), ('GENERAL', 'General Enquiry'), ('ACCOUNT', 'Account Issue'), ('HARDWARE', 'Hardware Problem'), ('SOFTWARE', 'Software Issue')], db_index=True, default='GENERAL', help_text='The category of the issue.', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment related to the ticket (e.g., screenshot, log file).', null=True, upload_to=acme.models.ticket_attachment_path),
        ),
        migrations.AddField(
            model_name='ticket',
            name='machine',
            field=models.ForeignKey(blank=True, help_text='Select the specific machine related to this ticket, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='acme.machine'),
        ),
    ]
