# Generated by Django 5.2 on 2025-04-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0005_alter_ticket_options_remove_ticket_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
