# Generated by Django 5.2 on 2025-04-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0008_commentattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='serial_number',
        ),
    ]
