# Generated by Django 5.2 on 2025-04-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0009_remove_machine_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='location',
            field=models.CharField(default='Building A', max_length=100),
            preserve_default=False,
        ),
    ]
