# Generated by Django 5.2 on 2025-04-10 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0010_machine_last_maintenance_machine_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='machine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='installation_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='next_maintenance',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='acme.machine'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='last_maintenance',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='location',
            field=models.CharField(blank=True, help_text="Physical location of the machine (e.g., 'Shop Floor A', 'Building 2').", max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MachineMaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('preventive', 'Preventive Maintenance'), ('corrective', 'Corrective Maintenance'), ('predictive', 'Predictive Maintenance'), ('emergency', 'Emergency Repair')], max_length=20)),
                ('technician', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='acme.machine')),
            ],
        ),
    ]
